name: jcrg
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluent_ui: ^4.10.0
  url_launcher: ^6.1.7
  intl: 0.19.0
  file_picker: 8.1.7
  excel: ^2.0.2
  path_provider: ^2.0.14
  provider: ^6.0.5
  flutter_calendar_carousel: ^2.0.1
  syncfusion_flutter_calendar: ^28.1.37
  flutter_local_notifications: ^18.0.1
  easy_sidemenu: ^0.6.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Log/
